### ISSUE TITLE
Feature Request / Question: Is it possible to also use CPU-Temperature for fan-target speed?

### ISSUE THREAD

**Issue by SHU-red** [fightforlife/docker_hddfancontrol#5]
Sorry for this question here but i am using hddfancontrol via docker and it works like a charm.
Since ive recently been using my homeserver also to transcode video, i ran into problems with high CPU temperatures.
Could someone give me a hint what to do with my docker-compose-file to also monitor CPU?
I dont care if this mix of CPU and HDD temperatures may also lead to permanent higher fan speeds.
Im just not very into this topic and am wondering if there is a way to just add the device CPU similar to my hdds:

```
version: "3"
services:
  hddfancontrol:
    image: fred92/hddfancontrol:master
    container_name: hddfancontrol
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules:ro
    privileged: true
    cap_add:
      - SYS_MODULE
    environment:
      - DEVICES=/dev/sda1 /dev/sdb1 /dev/sdc1 /dev/sdc2 #POSSIBLE TO ADD CPU HERE???
      - PWM_DEVICES=/sys/class/hwmon/hwmon2/pwm1 /sys/class/hwmon/hwmon2/pwm2
      - PWM_START=70 80
      - PWM_STOP=20 30
      - MIN_TEMP=30
      - MAX_TEMP=50
      - MIN_FAN=15
      - INTERVALL=60
      - SPINDOWN_TIME=900
      - LOG_PATH=/var/log/hddfancontrol.log
 ```
